accounts_collection:
    path:       /
    defaults:   { _controller: AppBundle:Account:collection }

accounts_create:
    path:       /new
    defaults:   { _controller: AppBundle:Account:create }

accounts_update:
    path:       /{accountId}/edit
    defaults:   { _controller: AppBundle:Account:update }

accounts_delete:
    path:       /{accountId}/delete
    defaults:   { _controller: AppBundle:Account:delete }
