services:
    twig.extension.text:
        class: Twig_Extensions_Extension_Text
        tags:
            - { name: twig.extension }
    app.mail_collector:
        class: AppBundle\Service\MailCollectorService
        arguments:
            - @doctrine
            - null #user
            - "%nylas.message_endpoint%"
